### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by ThorPiratesson** [kurupted/google-maps-timeline-viewer#2]
OK - sorry if this is a stupid question because I've never used Google Cloud before.  I set up the API restricted key and everything and it's just the Dashboard page right now.

Where do I find "Save this project's index.html file anywhere you like, eg My Documents." - do I need to create the index.html file in the cloud first?  If so, how?  Thanks :(

**Comment by kurupted** [comment]
Hi,

No worries. You'll want to click on index,html, which takes you here:
https://github.com/kurupted/google-maps-timeline-viewer/blob/main/index.html

and then click on "Raw" in the top-right of the file content area. Goes here:
https://raw.githubusercontent.com/kurupted/google-maps-timeline-viewer/refs/heads/main/index.html

Copy all of that and paste it into Notepad. Save the file as whateveryouwant.html

**Comment by ThorPiratesson** [comment]
Oops... that was embarrassing... thanks! :D
