### ISSUE TITLE
Final Set Up help

### ISSUE THREAD

**Issue by wbeests** [kurupted/google-maps-timeline-viewer#4]
This may be a very simple question. I am not sure as I am very unfamiliar with Google Cloud Services. How do I export a index.html file from my google project? I am not sure where to find the option for this 

"Save this project's index.html file anywhere you like, eg My Documents. (Click the index.html file, then click on "Raw" in the top-right of the content area. Copy/paste to eg Notepad and save as index.html)"

Thanks!

**Comment by kurupted** [comment]
Oh the index.html isn't at Google, it's near the top of the page here on Github.

![image](https://github.com/user-attachments/assets/76733c01-5baa-4c7d-98e2-cffec9386dda)

**Comment by wbeests** [comment]
Ooooh wow my bad. Thankyou!
